FROM openjdk:11-jdk-slim-buster

RUN apt-get update && \
    apt-get install -y --fix-missing ffmpeg wget fontconfig unzip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir /spring
WORKDIR /spring

RUN wget https://github.com/orioncactus/pretendard/releases/download/v1.3.9/Pretendard-1.3.9.zip -O Pretendard.zip && \
    unzip Pretendard.zip -d /usr/share/fonts/pretendard && \
    fc-cache -fv && \
    rm Pretendard.zip

COPY build/libs/video-editing-service-0.0.1-SNAPSHOT.jar /spring/app.jar

ENTRYPOINT ["java", "-jar", "/spring/app.jar"]
